#!/usr/bin/env python3
"""Build the pull request body from agent state."""
import json
import os
from pathlib import Path

headline = "(headline unavailable)"
narrative = "(no narrative provided)"
key_themes = "- (none)"
action_items = "- (none)"

state_path = Path("data/agent_state.json")
if state_path.exists():
    try:
        data = json.loads(state_path.read_text())
        latest = data.get("latest_brief") or {}
        headline = latest.get("headline") or headline
        narrative = latest.get("narrative") or narrative
        themes = latest.get("key_themes") or []
        actions = latest.get("action_items") or []
        if themes:
            key_themes = "\n".join(f"- {item}" for item in themes)
        if actions:
            action_items = "\n".join(f"- {item}" for item in actions)
    except Exception:
        pass

body = f"""## Summary
- Automated refresh of the CyberNews cybersecurity brief generated by the resident LLM agent.

### Latest headline
{headline}

### Narrative
{narrative}

### Key themes
{key_themes}

### Action items
{action_items}
""".strip()

with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as handle:
    handle.write("body<<'EOF'\n")
    handle.write(body + "\n")
    handle.write("EOF\n")
